import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectDirectory = fileURLToPath(new URL("../", import.meta.url));
const outputDirectory = path.join(projectDirectory, "out");

async function listFiles(directory, prefix = "") {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const relativePath = path.posix.join(prefix, entry.name);
      return entry.isDirectory()
        ? listFiles(path.join(directory, entry.name), relativePath)
        : [relativePath];
    }),
  );
  return nested.flat();
}

const files = (await listFiles(outputDirectory)).sort();
if (!files.includes("index.html") || !files.includes("manifest.webmanifest")) {
  throw new Error("The static export is incomplete. Run next build first.");
}

// Keep the complete build's assets together, including dynamically loaded chunks.
// Source maps, route payloads and unused HTML pages do not belong to this shell.
const assetFiles = files.filter(
  (file) =>
    (file.startsWith("_next/static/") &&
      /\.(?:js|css|woff2?|ttf|otf|png|jpe?g|webp|avif|svg|gif|ico)$/.test(file)) ||
    file.startsWith("icons/") ||
    file === "manifest.webmanifest" ||
    file === "favicon.ico" ||
    file === "opengraph-image.png",
);
const shell = [
  { url: "/", file: "index.html" },
  ...assetFiles.map((file) => ({ url: `/${file}`, file })),
];

// Include this script so a change in cache behavior also gets a fresh cache.
const hash = createHash("sha256").update(await readFile(fileURLToPath(import.meta.url)));
for (const entry of shell) {
  hash.update(entry.url).update(await readFile(path.join(outputDirectory, entry.file)));
}
const version = hash.digest("hex").slice(0, 16);

const source = `// Generated by scripts/generate-sw.mjs; do not edit.
const CACHE_PREFIX = "quiet-time-shell-";
const CACHE_NAME = CACHE_PREFIX + ${JSON.stringify(version)};
const APP_SHELL = ${JSON.stringify(shell.map((entry) => entry.url), null, 2)};
const ASSETS = new Set(APP_SHELL.filter((url) => url !== "/"));

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll(APP_SHELL.map((url) => new Request(url, { cache: "reload" }))),
    ),
  );
  // No skipWaiting: an update must not replace assets used by an open page.
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
      .map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== "GET" || url.origin !== self.location.origin) return;

  const isHomeNavigation = request.mode === "navigate" &&
    (url.pathname === "/" || url.pathname === "/index.html");
  if (!isHomeNavigation && !ASSETS.has(url.pathname)) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE_NAME);
    const cached = await cache.match(isHomeNavigation ? "/" : url.pathname);
    // Serve the HTML from this worker's build online and offline alike. This
    // prevents a newer document from requesting chunks absent from this cache.
    return cached || fetch(request);
  })());
});
`;

await writeFile(path.join(outputDirectory, "sw.js"), source);
console.log(`Generated sw.js (${shell.length} cached files, version ${version}).`);
